coverage:
  precision: 2
  round: down
  range: '10...90'
  status:
    project:
      default:
        target: 96%
        threshold: 2%
    patch:
      default:
        target: 90%
        threshold: 5%

comment:
  layout: 'condensed_header, condensed_files, condensed_footer'
  require_changes: true

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: unit
      paths:
        - core/src/

ignore:
  - '**/tests/**/*'
  - 'coverage/**/*'
